[
  "Love is not about possession, it's about appreciation.",
  "The best thing to hold onto in life is each other.",
  "True love stories never have endings.",
  "Love is when the other person's happiness is more important than your own.",
  "We loved with a love that was more than love.",
  "प्यार देने से बढ़ता है, बाँटने से कम नहीं होता।",
  "सच्चा प्यार कभी खत्म नहीं होता, वह हमेशा यादों में जिंदा रहता है।",
  "प्यार एक ऐसी भाषा है जिसे बहरे भी सुन सकते हैं और अंधे भी देख सकते हैं।",
  "जहाँ प्यार होता है, वहाँ जीवन होता है।",
  "प्यार सिर्फ एक शब्द नहीं, यह एक पूरी कहानी है।",
  "Love is composed of a single soul inhabiting two bodies.",
  "To love and be loved is to feel the sun from both sides.",
  "Love doesn't make the world go round. Love is what makes the ride worthwhile.",
  "The giving of love is an education in itself.",
  "Where there is love there is life.",
  "प्यार वो नहीं जो आप महसूस करते हैं, प्यार वो है जो आप करते हैं।",
  "प्यार में गिरना आसान है, लेकिन उसमें खड़े रहना सच्चा कौशल है।",
  "सच्चा प्यार कभी नहीं मरता, वह हमेशा दिल में जिंदा रहता है।",
  "प्यार एक ऐसा फूल है जिसे विश्वास की धूप चाहिए।",
  "जिस दिल में प्यार होता है, वह हमेशा जवान रहता है।",
  "Love is the master key that opens the gates of happiness.",
  "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
  "Love is friendship that has caught fire.",
  "The art of love is largely the art of persistence.",
  "We are most alive when we're in love.",
  "प्यार खोजने की चीज़ नहीं, बल्कि होने की अवस्था है।",
  "प्यार में समय नहीं देखा जाता, बस महसूस किया जाता है।",
  "प्यार वो मधुर संगीत है जिसे दो दिल मिलकर बजाते हैं।",
  "प्यार एक ऐसा रंग है जो हर चीज़ को खूबसूरत बना देता है।",
  "जहाँ प्यार हो वहाँ हमेशा बसंत रहता है।",
  "Love isn't something you find. Love is something that finds you.",
  "There is no remedy for love but to love more.",
  "Love is like the wind, you can't see it but you can feel it.",
  "A life without love is like a tree without blossoms or fruit.",
  "Love is the only force capable of transforming an enemy into a friend.",
  "प्यार दिल की वो भाषा है जिसमें सारे राज छुपे होते हैं।",
  "प्यार एक ऐसा उपहार है जो देने से बढ़ता है।",
  "प्यार में डूब जाओ तो गहराई का अहसास होता है, डर नहीं।",
  "प्यार वो नशा है जिसका कोई हंगामा नहीं होता।",
  "जिस दिल में प्यार बस जाए, वो दिल कभी अकेला नहीं होता।",
  "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.",
  "Love does not dominate; it cultivates.",
  "To love is nothing. To be loved is something. But to love and be loved, that's everything.",
  "Love is like a friendship caught on fire.",
  "The best love is the kind that awakens the soul.",
  "प्यार एक ऐसा सफर है जिसमें मंज़िल नहीं, साथ चलना ज़रूरी है।",
  "प्यार में खोना ही सबसे बड़ा पाना है।",
  "प्यार वो दवा है जो हर दर्द को भुला देती है।",
  "प्यार की कोई उम्र नहीं होती, वह हमेशा जवान रहता है।",
  "जिस राह में प्यार हो, वह राह हमेशा खूबसूरत होती है।",
  "Love is the poetry of the senses.",
  "Love is when you meet someone who tells you something new about yourself.",
  "Love is the greatest refreshment in life.",
  "Love is an irresistible desire to be irresistibly desired.",
  "Love is the flower you've got to let grow.",
  "प्यार वो नहीं जो आप देखते हैं, प्यार वो है जो आप महसूस करते हैं।",
  "प्यार एक ऐसा जादू है जो सब कुछ संभव बना देता है।",
  "प्यार में गिरने से मत डरो, क्योंकि यही गिरना उड़ने जैसा है।",
  "प्यार दो आत्माओं का मिलन है, जो एक दूसरे को पूरा करती हैं।",
  "जहाँ प्यार होता है, वहाँ कोई दूरी नहीं होती।",
  "Love is the voice under all silences, the hope which has no opposite in fear.",
  "Love is the magician that pulls man out of his own hat.",
  "Love is the emblem of eternity; it confounds all notion of time.",
  "Love is the beauty of the soul.",
  "Love is the only gold.",
  "प्यार एक ऐसा रिश्ता है जिसमें दो दिल एक हो जाते हैं।",
  "प्यार वो मधुर संगीत है जो दो दिल मिलकर बजाते हैं।",
  "प्यार में खो जाना ही सच्चा पाना है।",
  "प्यार एक ऐसा उपहार है जो हमेशा के लिए रहता है।",
  "जिस दिल में प्यार हो, वह दिल कभी नहीं डरता।",
  "Love is the bridge between you and everything.",
  "Love is the only reality and it is not a mere sentiment.",
  "Love is the master key that opens the gates of happiness.",
  "Love is the extremely difficult realization that something other than oneself is real.",
  "Love is the triumph of imagination over intelligence.",
  "प्यार एक ऐसा रिश्ता है जिसमें दो आत्माएँ एक हो जाती हैं।",
  "प्यार वो नहीं जो आप खोजते हैं, प्यार वो है जो आपको ढूंढ लेता है।",
  "प्यार एक ऐसा फूल है जो विश्वास की धूप में खिलता है।",
  "प्यार में डूब जाने से मत डरो, क्योंकि यही तो असली जीवन है।",
  "जहाँ प्यार होता है, वहाँ हर चीज़ संभव हो जाती है।",
  "Love is the only sane and satisfactory answer to the problem of human existence.",
  "Love is the condition in which the happiness of another person is essential to your own.",
  "Love is the active concern for the life and the growth of that which we love.",
  "Love is the joy of the good, the wonder of the wise, the amazement of the gods.",
  "Love is the only light that can truly penetrate the darkness of fear.",
  "प्यार एक ऐसा सफर है जिसमें हर कदम मधुर होता है।",
  "प्यार वो नहीं जो आप देखते हैं, प्यार वो है जो आप महसूस करते हैं।",
  "प्यार एक ऐसा जादू है जो सब कुछ संभव बना देता है।",
  "प्यार में गिरने से मत डरो, क्योंकि यही गिरना उड़ने जैसा है।",
  "प्यार दो आत्माओं का मिलन है, जो एक दूसरे को पूरा करती हैं।",
  "Love is the voice under all silences, the hope which has no opposite in fear.",
  "Love is the magician that pulls man out of his own hat.",
  "Love is the emblem of eternity; it confounds all notion of time.",
  "Love is the beauty of the soul.",
  "Love is the only gold.",
  "प्यार एक ऐसा रिश्ता है जिसमें दो दिल एक हो जाते हैं।",
  "प्यार वो मधुर संगीत है जो दो दिल मिलकर बजाते हैं।",
  "प्यार में खो जाना ही सच्चा पाना है।",
  "प्यार एक ऐसा उपहार है जो हमेशा के लिए रहता है।",
  "जिस दिल में प्यार हो, वह दिल कभी नहीं डरता।",
  "Love is the bridge between you and everything.",
  "Love is the only reality and it is not a mere sentiment.",
  "Love is the master key that opens the gates of happiness.",
  "Love is the extremely difficult realization that something other than oneself is real.",
  "Love is the triumph of imagination over intelligence."
]