[
  "Believe in yourself.",
  "Success is not final; failure is not fatal.",
  "Dream big and dare to fail.",
  "You are stronger than you think.",
  "The best way out is always through.",
  "You cannot change what you are, only what you do.",
  "Every day is a new beginning.",
  "Happiness is not something ready-made; it comes from your actions.",
  "Hope is the most exciting thing there is in life.",
  "Say something positive, and you’ll see something positive.",
  "Every strike brings me closer to the next home run.",
  "Push yourself, because no one else is going to do it for you.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream it. Wish it. Do it.",
  "Great things never come from comfort zones.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible.",
  "Don’t wait for opportunity. Create it.",
  "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
  "The key to success is to focus on goals, not obstacles.",
  "Dream bigger. Do bigger.",
  "Don’t limit your challenges. Challenge your limits.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Start where you are. Use what you have. Do what you can.",
  "Your only limit is your mind.",
  "Doubt kills more dreams than failure ever will.",
  "Discipline is doing it even when you don’t feel like it.",
  "Don’t fear failure. Fear being in the exact same place next year.",
  "Action is the foundational key to all success.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Your life only gets better when you get better.",
  "Success starts with self-discipline.",
  "The difference between ordinary and extraordinary is that little extra.",
  "If it doesn’t challenge you, it won’t change you.",
  "Do not give up. The beginning is always the hardest.",
  "Work hard in silence. Let success be your noise.",
  "If you get tired, learn to rest — not to quit.",
  "When you feel like quitting, think about why you started.",
  "Believe you can, and you’re halfway there.",
  "Stay focused and never give up.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Strive for progress, not perfection.",
  "Be stronger than your excuses.",
  "Hard work beats talent when talent doesn’t work hard.",
  "Act as if what you do makes a difference. It does.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "Opportunities don’t happen. You create them.",
  "Don’t be afraid to give up the good to go for the great.",
  "I find that the harder I work, the more luck I seem to have.",
  "Try not to become a man of success. Rather become a man of value.",
  "I never dreamed about success, I worked for it.",
  "A goal without a plan is just a wish.",
  "Don’t let what you cannot do interfere with what you can do.",
  "Do what you can with all you have, wherever you are.",
  "It always seems impossible until it is done.",
  "Go as far as you can see; when you get there, you’ll be able to see further.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Whether you think you can or think you can’t, you’re right.",
  "There is no elevator to success. You have to take the stairs.",
  "Don’t count the days, make the days count.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "You don’t have to see the whole staircase, just take the first step.",
  "The only place where success comes before work is in the dictionary.",
  "Failure is not the opposite of success; it’s part of success.",
  "Learn as if you will live forever, live like you will die tomorrow.",
  "Do one thing every day that scares you.",
  "If you want something you’ve never had, you must be willing to do something you’ve never done.",
  "Success isn’t overnight. It’s when every day you get a little better than the day before.",
  "Energy and persistence conquer all things.",
  "If you’re going through hell, keep going.",
  "You miss 100% of the shots you don’t take.",
  "Your time is limited, so don’t waste it living someone else’s life.",
  "Stay hungry. Stay foolish.",
  "Turn your wounds into wisdom.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Focus on being productive instead of busy.",
  "The secret of getting ahead is getting started.",
  "Don’t let yesterday take up too much of today.",
  "Success doesn’t come from what you do occasionally. It comes from what you do consistently.",
  "Greatness only comes before hustle in the dictionary.",
  "You are never too old to set another goal or to dream a new dream.",
  "Sometimes later becomes never. Do it now.",
  "You don’t grow when you’re comfortable.",
  "Success is not how high you have climbed, but how you make a positive difference.",
  "Always do your best. What you plant now, you will harvest later.",
  "The best revenge is massive success.",
  "A river cuts through rock not because of its power, but because of its persistence.",
  "Be so good they can’t ignore you.",
  "Start small. Think big. Don’t stop.",
  "Even if you fall on your face, you’re still moving forward.",
  "Never let success get to your head. Never let failure get to your heart.",
  "Make each day your masterpiece.",
  "Don’t limit yourself. You can go as far as your mind lets you.",
  "Today is your opportunity to build the tomorrow you want.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Success is not in what you have, but who you are."
]
