[
  "Believe you can and you're halfway there.",
  "Your only limit is your mind.",
  "Push yourself, because no one else is going to do it for you.",
  "Dream it. Wish it. Do it.",
  "Success doesn’t just find you. You have to go out and get it.",
  "Great things never come from comfort zones.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Don’t watch the clock; do what it does. Keep going.",
  "Stay focused and never give up.",
  "Don’t stop until you’re proud.",
  "Doubt kills more dreams than failure ever will.",
  "Little by little, day by day, what is meant for you will find its way.",
  "Discipline is choosing between what you want now and what you want most.",
  "It always seems impossible until it's done.",
  "Work hard in silence, let success be your noise.",
  "You are capable of amazing things.",
  "Success is what happens after you’ve survived all your mistakes.",
  "Believe in yourself and all that you are.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Be stronger than your excuses.",
  "If you get tired, learn to rest, not quit.",
  "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
  "Don’t be afraid to start over. It’s a chance to build something better.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "Strive for progress, not perfection.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Start where you are. Use what you have. Do what you can.",
  "Act as if what you do makes a difference. It does.",
  "A little progress each day adds up to big results.",
  "Don’t limit your challenges. Challenge your limits.",
  "If it doesn’t challenge you, it won’t change you.",
  "Success is not for the lazy.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Failure is not the opposite of success; it’s part of success.",
  "Big journeys begin with small steps.",
  "The secret of getting ahead is getting started.",
  "Stay hungry. Stay foolish.",
  "Be the energy you want to attract.",
  "Don’t wait for opportunity. Create it.",
  "Work until your idols become your rivals.",
  "Every accomplishment starts with the decision to try.",
  "If you believe in it, then fight for it.",
  "Success starts with self-discipline.",
  "Make your life a masterpiece.",
  "Nothing worth having comes easy.",
  "Dare to dream big.",
  "Winners are not afraid of losing. But losers are.",
  "Turn your wounds into wisdom.",
  "You didn’t come this far to only come this far.",
  "Start today, not tomorrow.",
  "Strength grows in the moments when you think you can’t go on but you keep going anyway.",
  "Chase your passion, not your pension.",
  "A winner is a dreamer who never gives up.",
  "Stay positive. Work hard. Make it happen.",
  "Don’t call it a dream, call it a plan.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Fear is temporary. Regret is forever.",
  "Go the extra mile. It’s never crowded.",
  "When you feel like quitting, think about why you started.",
  "The comeback is always stronger than the setback.",
  "Turn the pain into power.",
  "Impossible is just an opinion.",
  "If you can’t find a way, create one.",
  "You are your only limit.",
  "Fall seven times, stand up eight.",
  "The best view comes after the hardest climb.",
  "Let your dreams be bigger than your fears.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Focus on the step in front of you, not the whole staircase.",
  "You become what you believe.",
  "Stop doubting yourself. Work hard and make it happen.",
  "Make it happen. Shock everyone.",
  "Don’t wait. The time will never be just right.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "One day or day one. You decide.",
  "Mindset is everything.",
  "Whatever you do, never run back to what broke you.",
  "Hustle in silence and let your success make the noise.",
  "Every great achievement was once considered impossible.",
  "Rise up. Start fresh. See the bright opportunity in each new day.",
  "There is no elevator to success—you have to take the stairs.",
  "Your future needs you. Your past doesn’t.",
  "Don't be busy, be productive.",
  "Be so good they can’t ignore you.",
  "You don’t grow when things are easy. You grow when you face challenges.",
  "Make every day count.",
  "Success is a series of small wins.",
  "Go for it. Whether it ends good or bad, it was an experience.",
  "Create a life you don’t need a vacation from.",
  "Start strong. Finish stronger.",
  "You’re not too old, and it’s not too late.",
  "Progress is progress, no matter how small.",
  "Keep your dreams alive.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "The best way to get things done is to simply begin.",
  "Live your potential, not your limitations.",
  "You’re stronger than you think.",
  "Success begins with self-belief.",
  "Don’t just talk about it. Be about it.",
  "Make your vision so clear that your fears become irrelevant.",
  "Let today be the start of something new.",
  "Your vibe attracts your tribe.",
  "Work hard. Stay humble. Be kind."
]
