[
  "Life is what happens when you're busy making other plans.",
  "In the middle of every difficulty lies opportunity.",
  "Life is short. Make it count.",
  "Live life to the fullest, and focus on the positive.",
  "The purpose of life is to live it, to taste experience to the utmost.",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away.",
  "Keep your eyes on the stars and your feet on the ground.",
  "Life is a journey, not a destination.",
  "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
  "Life is really simple, but we insist on making it complicated.",
  "Difficult roads often lead to beautiful destinations.",
  "Make your life a masterpiece; imagine no limitations.",
  "Life doesn’t have to be perfect to be beautiful.",
  "Enjoy the little things in life, for one day you’ll look back and realize they were the big things.",
  "Life is like riding a bicycle. To keep your balance, you must keep moving.",
  "Be happy for this moment. This moment is your life.",
  "Don’t go through life, grow through life.",
  "Live as if you were to die tomorrow. Learn as if you were to live forever.",
  "Life is not about waiting for the storm to pass, but learning to dance in the rain.",
  "Smile, breathe, and go slowly.",
  "Sometimes the wrong choices bring us to the right places.",
  "Life isn’t about finding yourself. It’s about creating yourself.",
  "Make each day your masterpiece.",
  "Life is made of ever so many partings welded together.",
  "The good life is one inspired by love and guided by knowledge.",
  "To live is the rarest thing in the world. Most people just exist.",
  "Life is either a daring adventure or nothing at all.",
  "Life becomes easier when you learn to accept things you cannot change.",
  "The best way to prepare for life is to begin to live.",
  "Life is a reflection of your thoughts. Think positive.",
  "A meaningful life is not being rich, being popular, being highly educated or being perfect. It’s about being real, being humble and being kind.",
  "Life teaches you more than school ever will.",
  "Life is tough, but so are you.",
  "No matter how you feel, get up, dress up, show up, and never give up.",
  "Sometimes life hits you in the head with a brick. Don’t lose faith.",
  "Appreciate where you are in your journey, even if it’s not where you want to be yet.",
  "Take the risk or lose the chance.",
  "Life is 10% what happens to you and 90% how you react to it.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Life is too important to be taken seriously.",
  "Live your truth. Express your love. Share your enthusiasm. Take action towards your dreams.",
  "Life is short, and it's up to you to make it sweet.",
  "Every day is a second chance.",
  "You only live once, but if you do it right, once is enough.",
  "The best time for new beginnings is now.",
  "The biggest adventure you can take is to live the life of your dreams.",
  "When nothing goes right, go left.",
  "Life doesn’t require that we be the best, only that we try our best.",
  "Enjoy life now. This is not a rehearsal.",
  "Life is not about how fast you run or how high you climb but how well you bounce.",
  "Life begins at the end of your comfort zone.",
  "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
  "Don’t be pushed by your problems. Be led by your dreams.",
  "The most beautiful thing about life is that it goes on.",
  "Live less out of habit and more out of intent.",
  "Life is a balance of holding on and letting go.",
  "Don’t count the days. Make the days count.",
  "The simple things are also the most extraordinary things.",
  "Life rewards those who take risks.",
  "Life is too short to wait.",
  "Everything in life is temporary. Be grateful while it lasts.",
  "Don’t let life discourage you; everyone who got where they are had to begin where they were.",
  "Life is about making an impact, not making an income.",
  "Do more things that make you forget to check your phone.",
  "Happiness is not by chance, but by choice.",
  "Life is the flower for which love is the honey.",
  "Sometimes the smallest step in the right direction ends up being the biggest step of your life.",
  "Live boldly. Push yourself. Don’t settle.",
  "Life is too deep for words, so don’t try to describe it. Just live it.",
  "Life’s too mysterious to take too serious.",
  "You have to fight through some bad days to earn the best days of your life.",
  "No pressure, no diamonds.",
  "Don’t let the fear of losing be greater than the excitement of winning.",
  "In three words I can sum up everything I’ve learned about life: it goes on.",
  "Life is not always easy, but it’s always worth it.",
  "Life doesn’t come with instructions. You just do your best.",
  "You were given this life because you’re strong enough to live it.",
  "Life is an echo. What you send out, comes back.",
  "To love and be loved is to feel the sun from both sides.",
  "Let your life be your message.",
  "Don't just exist — live.",
  "Make your life story so inspiring that someone else wants to write a book about it.",
  "Everything happens for a reason. Just trust the process.",
  "Live the life you’ve imagined.",
  "There is beauty in simplicity.",
  "Collect moments, not things.",
  "Life is a beautiful struggle.",
  "The best things in life aren’t things.",
  "Success in life is not in what you have but who you become.",
  "Life is the art of drawing without an eraser.",
  "Go confidently in the direction of your dreams. Live the life you’ve imagined.",
  "Live every moment. Laugh every day. Love beyond words.",
  "Life is better when you’re laughing.",
  "Do not follow where the path may lead. Go instead where there is no path and leave a trail.",
  "Live with no excuses and love with no regrets.",
  "A great attitude becomes a great day which becomes a great life.",
  "Take every chance. Drop every fear.",
  "Life is about moments: don’t wait for them, create them.",
  "What a wonderful thought it is that some of the best days of our lives haven’t happened yet.",
  "Enjoy the ride — life is a rollercoaster.",
  "Don’t ruin a good today by thinking about a bad yesterday.",
  "Life is a mirror and will reflect back to the thinker what he thinks into it.",
  "Happiness is letting go of what you think your life is supposed to look like and celebrating it for everything that it is."
]
