[
  "I'm not lazy, I'm on energy-saving mode.",
  "I'm not arguing, I'm just explaining why I'm right.",
  "My bed and I love each other, only the alarm clock comes between us.",
  "If I were a bird, I know who I’d poop on.",
  "Brains are awesome. I wish everybody had one.",
  "I’m not short. I’m concentrated awesome.",
  "I'm not weird. I'm a limited edition.",
  "Life is short. Smile while you still have teeth.",
  "I need a six-month vacation, twice a year.",
  "Some people graduate with honors, I am just honored to graduate.",
  "Why fall in love when you can fall asleep?",
  "If stress burned calories, I’d be a supermodel.",
  "I'm not adulting today. Please try again tomorrow.",
  "Running late is my cardio.",
  "Common sense is like deodorant. The people who need it most never use it.",
  "If you can’t convince them, confuse them.",
  "I don’t have a dirty mind. I have a sexy imagination.",
  "I told my wife she should embrace her mistakes... She hugged me.",
  "I followed my heart… it led me to the fridge.",
  "Alcohol: Because no great story ever started with someone eating a salad.",
  "I love deadlines. I love the whooshing sound they make as they fly by.",
  "I’m not saying I hate you, but I would unplug your life support to charge my phone.",
  "Marriage is like a walk in the park... Jurassic Park.",
  "My favorite exercise is a cross between a lunge and a crunch... I call it lunch.",
  "If life gives you lemons, add vodka.",
  "Sarcasm is my cardio.",
  "I don’t rise and shine. I caffeinate and hope for the best.",
  "Some people bring happiness wherever they go, others whenever they go.",
  "I’m not antisocial, I’m selectively social.",
  "If I had a dollar for every time I got distracted... I wish I had a dog.",
  "Behind every angry woman stands a man who has absolutely no idea what he did wrong.",
  "My hobbies include eating and complaining that I’m getting fat.",
  "I used to be indecisive. Now I'm not sure.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Dear sleep, I'm sorry we broke up this morning. I want you back!",
  "I whisper to my WiFi router at night… 'Be strong, for tomorrow is Netflix.'",
  "Adulting is soup, and I am a fork.",
  "Sometimes I shock myself with the smart stuff I say. Then I try to remember where I heard it.",
  "I may be a terrible adult, but at least I'm great at napping.",
  "I put the 'pro' in procrastinate.",
  "If you can’t dazzle them with brilliance, baffle them with nonsense.",
  "I like long romantic walks… to the fridge.",
  "Can I get a refund on this adult life? I didn’t order this chaos.",
  "Whoever said nothing is impossible obviously never tried slamming a revolving door.",
  "I’m not drunk, I’m just chemically off-balanced.",
  "Wine is like duct tape—it fixes everything.",
  "Relationship status: Currently holding it together with coffee and sarcasm.",
  "Life’s too short to remove USB safely.",
  "I'm not clumsy, the floor just hates me.",
  "Flirtationship: More than a friendship, less than a relationship.",
  "I’m on a whiskey diet. I’ve lost three days already.",
  "Yoga class? I thought you said ‘Pour a glass.’",
  "Some people wake up with a purpose. I just wake up.",
  "Mondays should be optional.",
  "I’d agree with you but then we’d both be wrong.",
  "Don't give up on your dreams. Keep sleeping.",
  "I'm multitasking: I can listen, ignore and forget at the same time.",
  "Some days I amaze myself. Other days I put my keys in the fridge.",
  "I love sleep because it's like a time machine to breakfast.",
  "I thought I wanted a career. Turns out I just wanted a paycheck.",
  "I'm not addicted to coffee, we're just in a committed relationship.",
  "My level of sarcasm depends on your level of stupidity.",
  "Password is incorrect? Well, it was correct yesterday!",
  "My diet plan: Make all of my friends cookies; the fatter they get, the thinner I look.",
  "I have too many tabs open—both in my brain and my browser.",
  "I used to think I was indecisive, but now I'm not so sure.",
  "I’m not great at the advice. Can I interest you in a sarcastic comment?",
  "I wonder how many calories I burn just by jumping to conclusions.",
  "Netflix: Are you still watching? Me: Always and forever.",
  "They say don't try this at home… so I went to a friend’s house.",
  "Don't grow up, it's a trap.",
  "My phone battery lasts longer than most relationships these days.",
  "You can't have everything… where would you put it?",
  "I didn’t trip, I was just testing gravity.",
  "I'm not ignoring you, I'm just on airplane mode.",
  "I hate when people ask me what I’ll be doing in 5 years. I don’t have 2020 vision.",
  "Oops is always better than what if.",
  "If we’re not meant to have midnight snacks, why is there a light in the fridge?",
  "I love how coffee tricks me into thinking I'm in a good mood.",
  "Exercise? I thought you said extra fries!",
  "I plan to live forever. So far, so good.",
  "I’m not responsible for what my face does when you talk.",
  "I run on caffeine, chaos, and cuss words.",
  "My life feels like a test I didn’t study for.",
  "I love deadlines. Especially the whooshing sound they make as they fly by.",
  "I'm in shape. Round is a shape.",
  "Oops! My bad. I forgot you were an idiot.",
  "I clean when I’m angry. Which is why my house is a mess.",
  "I'm not a complete idiot—some parts are missing.",
  "Do I run? Yes… out of patience, money, and time.",
  "I'm not lazy, I just rest before I get tired.",
  "My mood depends on how good my hair looks.",
  "Let’s taco ‘bout how hungry I am.",
  "I am not lazy. I am on power-saving mode.",
  "I told myself I should stop drinking… but I’m not about to listen to a drunk who talks to themselves.",
  "You can’t scare me. I have a toddler.",
  "Sorry I’m late, I didn’t want to come.",
  "I’m not saying I’m Wonder Woman, I’m just saying no one has ever seen me and Wonder Woman in the same room.",
  "Nothing haunts us like the pizza we didn’t eat.",
  "Don’t be sad, just eat some fries and move on.",
  "Life is all about perspective. The Titanic sinking was a miracle to the lobsters in the ship’s kitchen."
]
