[
  "Yaqeen insaan ko pahadon se bhi buland kar deta hai.",
  "Mehnat woh kunji hai jo kaamyabi ke darwaaze kholti hai.",
  "Khwab woh nahi jo neend mein aayein, khwab woh hain jo neend uda dein.",
  "Hausla insaan ki sabse badi taqat hai.",
  "Kaamyabi ki pehli seedi khud aatmvishwas hai.",
  "Jo waqt ki kadar karta hai, waqt usse kaamyab banata hai.",
  "Andhere mein umeed ka chiraag jalana seekho.",
  "Dil saaf ho to dua bhi jaldi qubool hoti hai.",
  "Har mushkil ke baad aasani hai.",
  "Mohabbat khamoshi se bhi ki ja sakti hai.",
  "Waqt sabse bada ustaad hai.",
  "Khud ko pehchanna sabse badi samajhdari hai.",
  "Zindagi ka asal husn saadgi mein hai.",
  "Sachchai insaan ko kabhi tanha nahi chhodti.",
  "Doosron ke liye aasaniyaan paida karo, Allah tumhare liye raaste aasan karega.",
  "Mohabbat lafzon ki mohtaaj nahi hoti.",
  "Dil se nikli baat dil par asar karti hai.",
  "Ilm haasil karna har Musalman mard aur aurat par farz hai.",
  "Khushi baantne se badhti hai.",
  "Jo jaisa boyega, waisa hi kaatega.",
  "Phoolon ki khushboo hamesha nahi rehti, lekin nekion ki khushboo sada rehti hai.",
  "Insaan ki pehchan uske aamaal se hoti hai.",
  "Chhoti khushi ko mehsoos karna bhi ek kala hai.",
  "Muskurahat ek aisi dawai hai jo dil ka dard kam karti hai.",
  "Khamoshi bhi kabhi kabhi sab kuch keh jaati hai.",
  "Apne iraadon ko kabhi chhota mat samjho.",
  "Bure waqt ka matlab yeh nahi ki zindagi khatam ho gayi hai.",
  "Acha sochoge to acha hoga.",
  "Zindagi ek kitaab hai, har din ek naya panna hai.",
  "Har subah ek nayi umeed lekar aati hai.",
  "Jab tak thako mat, tab tak ruko mat.",
  "Hausla rakhne waale kabhi haarta nahi karte.",
  "Kamyabi sirf manzil nahi, ek safar hai.",
  "Duniya wohi badalti hai jo khud ko badalte hain.",
  "Chhoti chhoti baatein badi khushiyan deti hain.",
  "Apne sapno ko zinda rakhna seekho.",
  "Mitti se seekho, girkar uthna kya hota hai.",
  "Waqt sab kuch sikha deta hai, bas intezaar karna padta hai.",
  "Zindagi ka har lamha ek naya sabak deta hai.",
  "Galtiyaan sabse badi seekh hoti hain.",
  "Sabr ka phal hamesha meetha hota hai.",
  "Musibat mein jo saath de wahi asli apna hota hai.",
  "Apni auqat se zyada kabhi mat chaho.",
  "Aansu bhi kabhi kabhi dil halka kar dete hain.",
  "Jitna kam bolo, utna hi zyada log sunte hain.",
  "Duniya ko khush karna mushkil hai, khud ko khush rakho.",
  "Kisi ko zarurat se zyada izzat mat do, girne mein der nahi lagti.",
  "Jo waqt ke saath nahi chalta, waqt usse peechhe chhod deta hai.",
  "Dil jeetne ka tareeqa mohabbat hai, dikhawa nahi.",
  "Woh log kabhi nahi haarte jo kabhi haar maante hi nahi.",
  "Zindagi sirf sanson ka naam nahi, ehsaas bhi zaroori hai.",
  "Kamyabi milti hai unhein jo haar se darte nahi.",
  "Waqt har zakham bhar deta hai.",
  "Jitna daan doge, utni barkat milegi.",
  "Khushi paise se nahi, soch se milti hai.",
  "Jo mila hai usmein khushi dhoondo.",
  "Neki karna sabse bada insani farz hai.",
  "Mohabbat dil se hoti hai, surat se nahi.",
  "Achi soch achi zindagi banati hai.",
  "Simplicity is the ultimate sophistication.",
  "Jab tak zinda ho, tab tak seekhte raho.",
  "Mehnat kabhi zaya nahi jaati.",
  "Kisi ko neecha dikhakar kabhi ooncha nahi uth sakte.",
  "Raat jitni andheri ho, subah utni roshan hoti hai.",
  "Badi baatein karne se behtar hai chhoti chhoti nek baatein karna.",
  "Zindagi mein har kisi ko khush nahi kar sakte.",
  "Jise khud par bharosa hai, usse duniya hara nahi sakti.",
  "Behtareen log woh hote hain jo sirf apne liye nahi sochte.",
  "Dil se ki gayi dua kabhi khaali nahi jaati.",
  "Insaan ka asli chehra uske raavayye mein chhupa hota hai.",
  "Safalta ka raaz hai lagataar koshish.",
  "Har roz kuch naya seekhne ki koshish karo.",
  "Apne iraade mazboot rakho, manzil milkar rahegi.",
  "Andhera kitna bhi gehra ho, ek diya kaafi hota hai.",
  "Insaniyat sabse bada dharm hai.",
  "Jitna tum dusron ke liye karoge, utna hi khush rahoge.",
  "Zindagi sirf guzarne ka naam nahi, jeene ka hunar hai.",
  "Mohabbat wahi hai jo khamoshi mein bhi mehsoos ho.",
  "Hamesha un logon ke saath raho jo tumhare liye dua karte hain.",
  "Waqt ke saath chalna seekho, waqt kisi ka intezaar nahi karta.",
  "Jo log dil se madad karte hain, woh hamesha yaad rehte hain.",
  "Khud se mohabbat karo, duniya khud-b-khud pyar karegi.",
  "Waqt sabka aata hai, bas intezaar zaroori hai.",
  "Jitni mohabat baaton se nahi hoti, utni nazar se hoti hai.",
  "Sabar aur shukr zindagi ke do pehlu hain.",
  "Waqt aur izzat dono milte hain, lekin sambhalkar rakhne padte hain.",
  "Zindagi mein asli jeet apne dar ko harane mein hai.",
  "Behtareen soch hamesha unchaiyon tak le jaati hai.",
  "Nafrat se zyada taqatwar hoti hai ek muskaan.",
  "Apne iraade asmaan jitne bade rakho.",
  "Kisi ka dil jeetna duniya jeetne se bada hai.",
  "Zindagi ek safar hai, manzil se zyada safar ka maza lo.",
  "Acha socho, acha hoga.",
  "Jo chhup kar dua karta hai, uski dua sabse pehle qubool hoti hai.",
  "Jitna kisi ki madad kar sakte ho, zaroor karo.",
  "Zindagi mein haar tab hoti hai jab aap koshish karna chhod dete ho.",
  "Kisi ke chhote kaam ki kadar karna seekho.",
  "Achchai mein hamesha takat hoti hai.",
  "Zindagi mein asli sukoon sirf Allah ki yaad mein hai.",
  "Waqt kisi ka bhi ho, guzarta zaroor hai.",
  "Zakhm dil ke ho ya jism ke, bharne mein waqt lagta hai.",
  "Mohabbat mein haq nahi, sirf samajh hoti hai.",
  "Jitna maaf kar sakte ho, utna bada ban jaoge.",
  "Zindagi har roz ek naya imtihaan leti hai.",
  "Mitti mein bhi sona chhupa hota hai, bas dekhne ki nazar chahiye.",
  "Har insaan mein ek kahani chhupi hoti hai, sunne waala chahiye."
]
